SDK-2265 Retrieve Receipt
getyoti/yoti-php-sdk pull request #323
Opened 2023-03-21 13:52 UTC by LuborRod

2023-09-11 09:39 UTC, saurabh-yoti requested changes

2024-06-19 09:19 UTC, mehmet-yoti commented on tests/DigitalIdentityClientTest.php
added test

2024-06-19 09:20 UTC, mehmet-yoti commented on tests/Identity/DigitalIdentityServiceTest.php
added test

2024-06-19 09:20 UTC, mehmet-yoti commented on src/Identity/DigitalIdentityService.php
> +        $response = (new RequestBuilder($this->config))
updated in previous prs.

2024-06-19 09:20 UTC, mehmet-yoti commented on src/Identity/WrappedReceipt.php
> +    private ?string $error;
updated in previous prs.

2024-06-19 09:20 UTC, mehmet-yoti commented on src/Identity/ReceiptItemKey.php
> +        $encryptedDataProto->mergeFromString($decodedProto);
updated in previous prs.

2024-06-20 13:37 UTC, saurabh-yoti approved these changes

2024-06-21 10:52 UTC, saurabh-yoti approved these changes

2024-06-21 14:15 UTC, merged